name: Escaner Bolsa USA

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 14-19 * * 1-5"

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar programa
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar escáner
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python scanner_nuevo.py
